febe:
  image:  registry.soon.build/fm/febe
  command: forever -w app.js
#  volumes:
#    - ./api:/app/api
#    - ./assets:/app/assets
#    - ./config:/app/config
#    - ./views:/app/views
  ports:
    - 1337:1337
  links:
    - redis
    - api
  environment:
    - NODE_ENV=compose
    - FM_API_URI=api:5000
    - REDIS_URI=redis://redis:6379
    - REDIS_CHANNEL=fm:events

api:
  image: quay.io/thisissoon/fm-api
  command: ./manage.py runserver
  ports:
    - "5000:5000"
  links:
    - postgres
    - redis
  environment:
    - SQLALCHEMY_DATABASE_URI=postgresql://soonfm:soonfm@postgres:5432/soonfm
    - GOOGLE_REDIRECT_URI=http://localhost:8000/
    - CORS_ACA_ORIGIN=http://localhost:8000
    - GOOGLE_CLIENT_ID=826576189197-4sr9fonm8vr6ora4mfgdtou6j3v69asq.apps.googleusercontent.com
    - GOOGLE_CLIENT_SECRET=HuJwtrN_tiE2qa4XsikjxnQr
    - CELERY_BROKER_URL=redis://redis:6379/0
    - REDIS_SERVER_URI=redis://redis:6379/
    - REDIS_DB=0
    - ECHONEST_API_KEY=CIJ9BRHQVCOULALBX

celery:
  image: quay.io/thisissoon/fm-api
  command: celery -A fm.tasks.app worker -l info -c 2
  links:
    - postgres
    - redis
  environment:
    - C_FORCE_ROOT=True
    - SQLALCHEMY_DATABASE_URI=postgresql://soonfm:soonfm@postgres:5432/soonfm
    - GOOGLE_REDIRECT_URI=http://localhost:8000/
    - CORS_ACA_ORIGIN=http://localhost:8000
    - GOOGLE_CLIENT_ID=826576189197-4sr9fonm8vr6ora4mfgdtou6j3v69asq.apps.googleusercontent.com
    - GOOGLE_CLIENT_SECRET=HuJwtrN_tiE2qa4XsikjxnQr
    - CELERY_BROKER_URL=redis://redis:6379/0
    - REDIS_SERVER_URI=redis://redis:6379/
    - REDIS_DB=0
    - ECHONEST_API_KEY=CIJ9BRHQVCOULALBX

postgres:
  image: soon/docker-postgresql
  ports:
    - "5432:5432"
  expose:
    - "5432"
  environment:
    - POSTGRESQL_USER=soonfm
    - POSTGRESQL_PASS=soonfm
    - POSTGRESQL_DB=soonfm

redis:
  image: redis
  ports:
    - "6379:6379"
  expose:
    - "6379"
